// Canonical DEFAULT_SELECTORS — copied from automation-extension/content/panel-automation.js
// These are the TioRico defaults. Client profiles only need to override keys that differ.
export const DEFAULT_SELECTORS: Record<string, string> = {
  LOGIN_USERNAME_INPUT: 'input[type="text"][aria-label="Nombre de Usuario"], input[name="username"], input[name="user"], input[type="text"][placeholder*="suario"], input[type="text"][placeholder*="ombre"]',
  LOGIN_PASSWORD_INPUT: 'input[type="password"][aria-label="Contraseña"], input[name="password"], input[type="password"]',
  LOGIN_SUBMIT_BUTTON: 'button[type="submit"], input[type="submit"]',
  USER_MENU: 'li.user-toggle, .user-toggle.dropdown, span.own-username, .user-menu, [data-user], .profile, .navbar .dropdown, .navbar-nav .dropdown, .sidebar-header',
  LOGOUT_LINK: 'a[href*="logout"], a[href*="salir"], a[href*="cerrar"]',
  USERS_PAGE_LINK: 'a.mdbvue-sidenav__item[href*="/users"], a[href*="users.php"], a[href*="users"], a[href*="/users"]',
  USER_SEARCH_INPUT: '#filter-input, input[name="filter"], input[name="search"], input[name="q"], input[placeholder*="uscar"], input[placeholder*="iltrar"], input[type="search"]',
  ADD_CREDITS_BUTTON_ROW: 'a.action-plus',
  ADD_CREDITS_BUTTON_ICON: 'a .fas.fa-plus, a .fa.fa-plus, a .fa-plus, a i.fas.fa-plus, a i.fa.fa-plus',
  SUBTRACT_CREDITS_BUTTON_ROW: 'a.action-minus',
  DATATABLE_PROCESSING: '#DataTables_Table_0_processing, .dataTables_processing',
  MODAL: '.widthdraw.modal, .modal.show, .modal[style*="display: block"], [role="dialog"], .modal-dialog, .swal2-container',
  MODAL_AMOUNT_INPUT: '.modal-body input[inputmode="decimal"], input[inputmode="decimal"], input[type="number"], input[name="amount"], input[name="credits"], input[name="monto"]',
  MODAL_AMOUNT_INPUT_FALLBACK: '.modal-body input[aria-label="Username"]:not([disabled]), input[aria-label="Username"]:not([disabled]), input:not([type="hidden"]):not([type="password"]):not([type="search"]):not([type="email"]):not([disabled])',
  MODAL_SUBMIT: '.modal-body button[type="submit"], .modal button[type="submit"]',
  SUCCESS_MESSAGE: '.alert-success, .toast-success, .swal2-success, .swal2-popup.swal2-show .swal2-html-container, .swal-text, .alert.alert-success, #success-message, .notification.is-success',
  ERROR_MESSAGE: '.alert-danger, .alert-error, .toast-error, .swal2-error, .swal2-popup.swal2-show .swal2-html-container, .swal-text, .alert.alert-danger, #error-message, .notification.is-danger',
  OWN_BALANCE: 'span.own-balance',
  NEW_USER_BUTTON: 'button.btn.btn-danger',
  NEW_USER_BUTTON_ICON: 'i.fas.fa-user-plus',
  NEW_USER_MODAL: '.insert-mo.modal',
  NEW_USER_NICKNAME_INPUT: '.insert-mo input[type="text"][aria-label="Nickname"]',
  NEW_USER_PASSWORD_INPUT: '.insert-mo input[type="password"][aria-label="Contraseña"]',
  NEW_USER_SUBMIT: '.insert-mo button[type="submit"].btn.btn-cyan',
  NEW_USER_CANCEL: '.insert-mo button.btn.btn-outline-cyan',
  CHANGE_PASSWORD_BUTTON: 'a.action-password',
  PASSWORD_MODAL: '.insert-mo.modal',
  PASSWORD_INPUT: '.insert-mo input[type="password"][aria-label="Contraseña"], .modal-body input[type="password"]:first-of-type',
  PASSWORD_CONFIRM_INPUT: '.insert-mo input[type="password"][aria-label="Confirmación Contraseña"], .modal-body input[type="password"]:nth-of-type(2)',
  PASSWORD_SUBMIT: '.insert-mo button.btn.btn-cyan, .modal-body button[type="submit"]',
}

// Selector categories for the editor UI
export const SELECTOR_CATEGORIES = {
  'Autenticación': ['LOGIN_USERNAME_INPUT', 'LOGIN_PASSWORD_INPUT', 'LOGIN_SUBMIT_BUTTON'],
  'Navegación': ['USER_MENU', 'LOGOUT_LINK', 'USERS_PAGE_LINK'],
  'Búsqueda': ['USER_SEARCH_INPUT'],
  'Créditos': ['ADD_CREDITS_BUTTON_ROW', 'ADD_CREDITS_BUTTON_ICON', 'SUBTRACT_CREDITS_BUTTON_ROW'],
  'Modal': ['MODAL', 'MODAL_AMOUNT_INPUT', 'MODAL_AMOUNT_INPUT_FALLBACK', 'MODAL_SUBMIT', 'DATATABLE_PROCESSING'],
  'Notificaciones': ['SUCCESS_MESSAGE', 'ERROR_MESSAGE'],
  'Info': ['OWN_BALANCE'],
  'Crear Usuario': ['NEW_USER_BUTTON', 'NEW_USER_BUTTON_ICON', 'NEW_USER_MODAL', 'NEW_USER_NICKNAME_INPUT', 'NEW_USER_PASSWORD_INPUT', 'NEW_USER_SUBMIT', 'NEW_USER_CANCEL'],
  'Cambiar Password': ['CHANGE_PASSWORD_BUTTON', 'PASSWORD_MODAL', 'PASSWORD_INPUT', 'PASSWORD_CONFIRM_INPUT', 'PASSWORD_SUBMIT'],
} as const

// Required selectors — these must be defined for automation to work
export const REQUIRED_SELECTORS = new Set([
  'LOGIN_USERNAME_INPUT',
  'LOGIN_PASSWORD_INPUT',
  'LOGIN_SUBMIT_BUTTON',
  'USERS_PAGE_LINK',
  'USER_SEARCH_INPUT',
  'ADD_CREDITS_BUTTON_ROW',
  'MODAL',
  'MODAL_AMOUNT_INPUT',
  'MODAL_SUBMIT',
  'SUCCESS_MESSAGE',
  'ERROR_MESSAGE',
  'OWN_BALANCE',
  'USER_MENU',
])

// Human-readable labels for selectors
export const SELECTOR_LABELS: Record<string, string> = {
  LOGIN_USERNAME_INPUT: 'Input de usuario (login)',
  LOGIN_PASSWORD_INPUT: 'Input de contraseña (login)',
  LOGIN_SUBMIT_BUTTON: 'Botón submit (login)',
  USER_MENU: 'Menú de usuario / perfil',
  LOGOUT_LINK: 'Link de cerrar sesión',
  USERS_PAGE_LINK: 'Link a página de usuarios',
  USER_SEARCH_INPUT: 'Input de búsqueda de usuarios',
  ADD_CREDITS_BUTTON_ROW: 'Botón agregar créditos (en fila)',
  ADD_CREDITS_BUTTON_ICON: 'Ícono del botón agregar créditos',
  SUBTRACT_CREDITS_BUTTON_ROW: 'Botón restar créditos (en fila)',
  DATATABLE_PROCESSING: 'Indicador de carga de DataTable',
  MODAL: 'Contenedor del modal',
  MODAL_AMOUNT_INPUT: 'Input de monto en modal',
  MODAL_AMOUNT_INPUT_FALLBACK: 'Input de monto (fallback)',
  MODAL_SUBMIT: 'Botón submit del modal',
  SUCCESS_MESSAGE: 'Mensaje de éxito',
  ERROR_MESSAGE: 'Mensaje de error',
  OWN_BALANCE: 'Balance propio del panel',
  NEW_USER_BUTTON: 'Botón crear usuario nuevo',
  NEW_USER_BUTTON_ICON: 'Ícono del botón crear usuario',
  NEW_USER_MODAL: 'Modal de crear usuario',
  NEW_USER_NICKNAME_INPUT: 'Input de nickname (nuevo usuario)',
  NEW_USER_PASSWORD_INPUT: 'Input de contraseña (nuevo usuario)',
  NEW_USER_SUBMIT: 'Botón submit (nuevo usuario)',
  NEW_USER_CANCEL: 'Botón cancelar (nuevo usuario)',
  CHANGE_PASSWORD_BUTTON: 'Botón cambiar contraseña',
  PASSWORD_MODAL: 'Modal de cambiar contraseña',
  PASSWORD_INPUT: 'Input de contraseña nueva',
  PASSWORD_CONFIRM_INPUT: 'Input de confirmar contraseña',
  PASSWORD_SUBMIT: 'Botón submit (cambiar contraseña)',
}
