import type { ClientConfig } from './types'

// ── Validation ───────────────────────────────────────────────────

/** Fields that BLOCK generation if missing — without these the deploy files are broken */
const BLOCKING_FIELDS: { key: string; label: string; path?: string }[] = [
  { key: 'id', label: 'ID del cliente' },
  { key: 'businessName', label: 'Nombre del negocio' },
  { key: 'apiUrl', label: 'API URL' },
  { key: 'gamePanelUrl', label: 'URL del Panel de Juego' },
  { key: 'botApiKey', label: 'Bot API Key' },
  { key: 'operatorApiKey', label: 'Operator API Key' },
  { key: 'validatorApiKey', label: 'Validator API Key' },
  { key: 'jwtSecret', label: 'JWT Secret' },
  { key: 'databaseUrl', label: 'Database URL', path: 'deployment.databaseUrl' },
]

/** Fields that generate a WARNING but don't block */
const WARNING_FIELDS: { key: string; label: string; path?: string }[] = [
  { key: 'chatWebUrl', label: 'Chat Web URL (afecta CORS)' },
  { key: 'landingUrl', label: 'Landing URL (afecta CORS)' },
  { key: 'cloudinaryUrl', label: 'Cloudinary URL', path: 'deployment.cloudinaryUrl' },
  { key: 'telegramBotToken', label: 'Telegram Bot Token', path: 'deployment.telegramBotToken' },
  { key: 'telegramChatId', label: 'Telegram Chat ID', path: 'deployment.telegramChatId' },
  { key: 'monitoringApiKey', label: 'Monitoring API Key' },
]

function getNestedValue(obj: Record<string, unknown>, path: string): unknown {
  return path.split('.').reduce((acc: unknown, key) => {
    if (acc && typeof acc === 'object') return (acc as Record<string, unknown>)[key]
    return undefined
  }, obj)
}

export interface ValidationResult {
  valid: boolean
  errors: string[]   // Blocking — generation will fail
  warnings: string[] // Advisory — generation proceeds
}

/**
 * Validate a config BEFORE generating deploy files.
 * Returns errors (blocking) and warnings (informational).
 */
export function validateBeforeGeneration(config: ClientConfig): ValidationResult {
  const errors: string[] = []
  const warnings: string[] = []

  for (const field of BLOCKING_FIELDS) {
    const value = field.path
      ? getNestedValue(config as unknown as Record<string, unknown>, field.path)
      : (config as unknown as Record<string, unknown>)[field.key]
    if (!value || (typeof value === 'string' && value.trim() === '')) {
      errors.push(field.label)
    }
  }

  for (const field of WARNING_FIELDS) {
    const value = field.path
      ? getNestedValue(config as unknown as Record<string, unknown>, field.path)
      : (config as unknown as Record<string, unknown>)[field.key]
    if (!value || (typeof value === 'string' && value.trim() === '')) {
      warnings.push(field.label)
    }
  }

  return { valid: errors.length === 0, errors, warnings }
}

// ── Helpers ──────────────────────────────────────────────────────

/**
 * Escape a value for safe inclusion in a .env file (double-quoted).
 * Handles: embedded quotes, dollar signs, backslashes, newlines.
 */
function escapeEnvValue(value: string | undefined | null): string {
  if (!value) return ''
  return value
    .replace(/\\/g, '\\\\')   // backslash first (so we don't double-escape)
    .replace(/"/g, '\\"')      // double quotes
    .replace(/\$/g, '\\$')    // dollar signs (prevent shell expansion)
    .replace(/\n/g, '\\n')    // newlines
    .replace(/\r/g, '\\r')    // carriage returns
}

/** Shorthand: wrap in quotes with escaping */
function envVal(value: string | undefined | null): string {
  return `"${escapeEnvValue(value)}"`
}

// ── Generators ───────────────────────────────────────────────────

export function generateBackendEnv(config: ClientConfig): string {
  const d = config.deployment
  const corsOrigin = [config.chatWebUrl, config.landingUrl].filter(Boolean).join(',') || '*'
  return `# ============================================
# ${config.businessName} — Backend API
# Generated by Client Manager
# ============================================

# Database
DATABASE_URL=${envVal(d.databaseUrl)}
DIRECT_URL=${envVal(d.databaseUrl)}

# JWT
JWT_SECRET=${envVal(config.jwtSecret)}
JWT_EXPIRES_IN="7d"

# Bot Integration
BOT_API_KEY=${envVal(config.botApiKey)}

# Operator Panel
OPERATOR_API_KEY=${envVal(config.operatorApiKey)}

# Validator
VALIDATOR_API_KEY=${envVal(config.validatorApiKey)}
VALIDATOR_URL="http://localhost:11434"

# Monitoring (Client Manager)
MONITORING_API_KEY=${envVal(config.monitoringApiKey)}

# CORS
CORS_ORIGIN=${envVal(corsOrigin)}

# Cloudinary
CLOUDINARY_URL=${envVal(d.cloudinaryUrl)}

# Telegram
TELEGRAM_BOT_TOKEN=${envVal(d.telegramBotToken)}
TELEGRAM_CHAT_ID=${envVal(d.telegramChatId)}

# Queue
QUEUE_COOLDOWN_MS="30000"
MAX_REQUESTS_PER_HOUR="10"

# Security
BCRYPT_ROUNDS="10"
RATE_LIMIT_TTL="60000"
RATE_LIMIT_MAX="100"

# Application
NODE_ENV="production"
PORT="3000"
LOG_LEVEL="info"

# Seed
SEED_MODE="production"
SEED_ADMIN_EMAIL="admin@${config.id}.com"
SEED_ADMIN_PASSWORD="CHANGE_ME_IMMEDIATELY"
SEED_OPERATOR_EMAIL="operator@${config.id}.com"
SEED_OPERATOR_PASSWORD="CHANGE_ME_IMMEDIATELY"
SEED_PANEL_NAME=${envVal(config.businessName)}
`
}

export function generateChatAppEnv(config: ClientConfig): string {
  return `# ${config.businessName} — Chat App
# Generated by Client Manager

EXPO_PUBLIC_API_URL=${config.apiUrl}/api
EXPO_PUBLIC_SOCKET_URL=${config.apiUrl}
`
}

export function generateExtensionConfig(config: ClientConfig): string {
  return JSON.stringify({
    backendUrl: config.apiUrl,
    apiKey: config.botApiKey,
    panelUrl: config.gamePanelUrl,
    panelPassword: config.defaultPanelPassword,
  }, null, 2)
}

export function generateRenderYaml(config: ClientConfig): string {
  const prefix = config.dockerImagePrefix || config.id
  return `# ${config.businessName} — Render Blueprint
# Generated by Client Manager

services:
  # Backend API
  - type: web
    name: ${prefix}-api
    runtime: docker
    plan: starter
    dockerfilePath: ./apps/backend-api/Dockerfile
    dockerContext: ./apps/backend-api
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ${prefix}-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: BOT_API_KEY
        value: "${config.botApiKey}"
      - key: OPERATOR_API_KEY
        value: "${config.operatorApiKey}"
      - key: VALIDATOR_API_KEY
        value: "${config.validatorApiKey}"
      - key: MONITORING_API_KEY
        value: "${config.monitoringApiKey}"
      - key: CLOUDINARY_URL
        value: "${config.deployment.cloudinaryUrl}"
      - key: NODE_ENV
        value: "production"
      - key: CORS_ORIGIN
        value: "${[config.chatWebUrl, config.landingUrl].filter(Boolean).join(',')}"

  # Chat Web
  - type: web
    name: ${prefix}-chat-web
    runtime: docker
    plan: starter
    dockerfilePath: ./Dockerfile
    dockerContext: ./apps/chat-app-web

  # Landing Page
  - type: web
    name: ${prefix}-landing
    runtime: docker
    plan: starter
    dockerfilePath: ./apps/landing-page/Dockerfile
    dockerContext: ./apps/landing-page

databases:
  - name: ${prefix}-db
    plan: starter
    databaseName: ${config.id.replace(/-/g, '_')}_db
    user: ${config.id.replace(/-/g, '_')}
`
}

export function generateDockerCompose(config: ClientConfig): string {
  const prefix = config.dockerImagePrefix || config.id
  const registry = config.dockerRegistry || 'local'
  return `# ${config.businessName} — Docker Compose
# Generated by Client Manager

version: '3.8'
services:
  api:
    image: ${registry}/${prefix}-api:latest
    build:
      context: ./apps/backend-api
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./clients/${config.id}/deploy/backend.env
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${config.id.replace(/-/g, '_')}_db
      POSTGRES_USER: ${config.id.replace(/-/g, '_')}
      POSTGRES_PASSWORD: CHANGE_ME
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  pgdata:
`
}

export function generateProvisionScript(config: ClientConfig): string {
  const user = config.vpsUser || config.id.replace(/-/g, '')
  const home = config.homeDirectory || `/opt/${user}`
  const prefix = config.servicePrefix || user
  return `#!/bin/bash
# ${config.businessName} — VPS Provisioning Script
# Generated by Client Manager
# Run as root on Ubuntu 24.04

set -e

# --- Configuration ---
APP_USER="${user}"
APP_HOME="${home}"
SERVICE_PREFIX="${prefix}"
PANEL_URL="${config.gamePanelUrl}"

echo "=== Provisioning ${config.businessName} ==="

# --- Create user ---
if ! id "$APP_USER" &>/dev/null; then
  useradd -m -d "$APP_HOME" -s /bin/bash "$APP_USER"
  echo "User $APP_USER created"
fi

# --- Install dependencies ---
apt-get update -qq
apt-get install -y -qq curl wget unzip docker.io docker-compose-v2

# --- Install Chrome ---
if ! command -v google-chrome &>/dev/null; then
  wget -q https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  apt-get install -y ./google-chrome-stable_current_amd64.deb
  rm google-chrome-stable_current_amd64.deb
  echo "Chrome installed"
fi

# --- Create directories ---
mkdir -p "$APP_HOME"/{chrome-data,extensions,logs,scripts}
chown -R "$APP_USER:$APP_USER" "$APP_HOME"

# --- Systemd service: Chrome for panel automation ---
cat > /etc/systemd/system/$SERVICE_PREFIX-chrome-panel.service <<EOF
[Unit]
Description=$SERVICE_PREFIX Chrome Panel Automation
After=network.target

[Service]
Type=simple
User=$APP_USER
Environment=DISPLAY=:99
ExecStart=/usr/bin/google-chrome \\
  --no-sandbox \\
  --disable-gpu \\
  --user-data-dir=$APP_HOME/chrome-data \\
  --load-extension=$APP_HOME/extensions/automation-extension \\
  "$PANEL_URL"
Restart=on-failure
RestartSec=10

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
echo "Systemd services created"

echo ""
echo "=== Provisioning complete ==="
echo "Next steps:"
echo "  1. Copy automation extension to $APP_HOME/extensions/"
echo "  2. Configure extension options (API URL, API Key)"
echo "  3. Start: systemctl start $SERVICE_PREFIX-chrome-panel"
echo "  4. Enable: systemctl enable $SERVICE_PREFIX-chrome-panel"
`
}

/**
 * All generators in one call.
 */
export interface GeneratedFiles {
  'backend.env': string
  'chat-app.env': string
  'extension-config.json': string
  'render.yaml': string
  'docker-compose.yml': string
  'provision.sh': string
}

/**
 * Generate all deploy files. Throws if validation fails (blocking errors).
 * Call validateBeforeGeneration() first to check without throwing.
 */
export function generateAllFiles(config: ClientConfig): GeneratedFiles {
  const validation = validateBeforeGeneration(config)
  if (!validation.valid) {
    throw new Error(`Campos requeridos faltantes: ${validation.errors.join(', ')}`)
  }
  return {
    'backend.env': generateBackendEnv(config),
    'chat-app.env': generateChatAppEnv(config),
    'extension-config.json': generateExtensionConfig(config),
    'render.yaml': generateRenderYaml(config),
    'docker-compose.yml': generateDockerCompose(config),
    'provision.sh': generateProvisionScript(config),
  }
}
