/**
 * WireGuard VPN config generator for Aurum.
 * Generates server and peer configurations.
 */

export interface VpnServerConfig {
  endpoint: string          // "vpn.miempresa.com:51820"
  privateKey: string
  publicKey: string
  subnet: string            // "10.0.0.0/24"
  listenPort: number        // 51820
  dns: string               // "1.1.1.1, 8.8.8.8"
  postUp: string            // iptables NAT rule
  postDown: string
}

export interface VpnPeer {
  id: string
  name: string
  type: 'admin' | 'operator' | 'machine'
  privateKey: string
  publicKey: string
  presharedKey: string
  assignedIp: string        // "10.0.0.2/32"
  enabled: boolean
  createdAt: string
}

export interface VpnConfig {
  server: VpnServerConfig
  peers: VpnPeer[]
  nextIp: number            // next available last octet (e.g. 3)
}

export const EMPTY_VPN_CONFIG: VpnConfig = {
  server: {
    endpoint: '',
    privateKey: '',
    publicKey: '',
    subnet: '10.0.0.0/24',
    listenPort: 51820,
    dns: '1.1.1.1, 8.8.8.8',
    postUp: 'iptables -A FORWARD -i wg0 -j ACCEPT; iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE',
    postDown: 'iptables -D FORWARD -i wg0 -j ACCEPT; iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE',
  },
  peers: [],
  nextIp: 2,
}

/** Generate server wg0.conf */
export function generateServerConf(config: VpnConfig): string {
  const { server, peers } = config

  let conf = `# Aurum VPN Server — WireGuard Config
# Generated by Aurum Client Manager
# Deploy to /etc/wireguard/wg0.conf on your VPN server

[Interface]
Address = 10.0.0.1/24
ListenPort = ${server.listenPort}
PrivateKey = ${server.privateKey}
PostUp = ${server.postUp}
PostDown = ${server.postDown}
`

  for (const peer of peers) {
    if (!peer.enabled) continue
    conf += `
# ${peer.name} (${peer.type})
[Peer]
PublicKey = ${peer.publicKey}
PresharedKey = ${peer.presharedKey}
AllowedIPs = ${peer.assignedIp}
`
  }

  return conf
}

/** Generate peer .conf file (for the client to import) */
export function generatePeerConf(server: VpnServerConfig, peer: VpnPeer): string {
  return `# ${peer.name} — WireGuard Config
# Generated by Aurum Client Manager
# Import in WireGuard app (Windows/Mac/iOS/Android)

[Interface]
PrivateKey = ${peer.privateKey}
Address = ${peer.assignedIp}
DNS = ${server.dns}

[Peer]
PublicKey = ${server.publicKey}
PresharedKey = ${peer.presharedKey}
Endpoint = ${server.endpoint}
AllowedIPs = 0.0.0.0/0
PersistentKeepalive = 25
`
}

/** Generate next available IP */
export function getNextIp(config: VpnConfig): string {
  return `10.0.0.${config.nextIp}/32`
}
