/**
 * Centralized status constants for the entire platform.
 * All apps should reference these instead of hardcoding status strings.
 */

export const REQUEST_STATUS = {
  PENDING_PROOF: 'PENDING_PROOF',
  VALIDATING: 'VALIDATING',
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  PENDING_MP_VERIFICATION: 'PENDING_MP_VERIFICATION',
  APPROVED: 'APPROVED',
  PROCESSING: 'PROCESSING',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED',
  REJECTED: 'REJECTED',
  CANCELLED: 'CANCELLED',
} as const;

export type RequestStatusType = typeof REQUEST_STATUS[keyof typeof REQUEST_STATUS];

export const JOB_STATUS = {
  QUEUED: 'QUEUED',
  PROCESSING: 'PROCESSING',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED',
} as const;

export type JobStatusType = typeof JOB_STATUS[keyof typeof JOB_STATUS];

export const CHAT_STATUS = {
  OPEN: 'OPEN',
  ASSIGNED: 'ASSIGNED',
  CLOSED: 'CLOSED',
} as const;

export const MESSAGE_TYPE = {
  USER: 'USER',
  OPERATOR: 'OPERATOR',
  SYSTEM: 'SYSTEM',
} as const;

export const USER_ROLE = {
  CLIENT: 'CLIENT',
  OPERATOR: 'OPERATOR',
  SENIOR_OPERATOR: 'SENIOR_OPERATOR',
  ADMIN: 'ADMIN',
} as const;

/** Statuses considered "active" (request in progress) */
export const ACTIVE_REQUEST_STATUSES: RequestStatusType[] = [
  REQUEST_STATUS.PENDING_PROOF,
  REQUEST_STATUS.VALIDATING,
  REQUEST_STATUS.PENDING_MP_VERIFICATION,
  REQUEST_STATUS.APPROVED,
  REQUEST_STATUS.PROCESSING,
];

/** Valid status transitions */
export const VALID_TRANSITIONS: Record<string, string[]> = {
  [REQUEST_STATUS.PENDING_PROOF]: [REQUEST_STATUS.VALIDATING, REQUEST_STATUS.REJECTED, REQUEST_STATUS.CANCELLED],
  [REQUEST_STATUS.VALIDATING]: [REQUEST_STATUS.PENDING_MP_VERIFICATION, REQUEST_STATUS.VALIDATION_FAILED, REQUEST_STATUS.REJECTED, REQUEST_STATUS.CANCELLED],
  [REQUEST_STATUS.VALIDATION_FAILED]: [REQUEST_STATUS.APPROVED, REQUEST_STATUS.REJECTED, REQUEST_STATUS.CANCELLED],
  [REQUEST_STATUS.PENDING_MP_VERIFICATION]: [REQUEST_STATUS.APPROVED, REQUEST_STATUS.REJECTED, REQUEST_STATUS.VALIDATION_FAILED, REQUEST_STATUS.CANCELLED],
  [REQUEST_STATUS.APPROVED]: [REQUEST_STATUS.PROCESSING, REQUEST_STATUS.FAILED, REQUEST_STATUS.REJECTED],
  [REQUEST_STATUS.PROCESSING]: [REQUEST_STATUS.COMPLETED, REQUEST_STATUS.FAILED],
  [REQUEST_STATUS.COMPLETED]: [],
  [REQUEST_STATUS.FAILED]: [REQUEST_STATUS.APPROVED, REQUEST_STATUS.PROCESSING],
  [REQUEST_STATUS.REJECTED]: [],
  [REQUEST_STATUS.CANCELLED]: [],
};

/** Human-readable labels (Spanish) */
export const REQUEST_STATUS_LABELS: Record<string, string> = {
  [REQUEST_STATUS.PENDING_PROOF]: 'Esperando comprobante',
  [REQUEST_STATUS.VALIDATING]: 'Validando',
  [REQUEST_STATUS.VALIDATION_FAILED]: 'Validacion fallida',
  [REQUEST_STATUS.PENDING_MP_VERIFICATION]: 'Verificando pago en MP',
  [REQUEST_STATUS.APPROVED]: 'Aprobado',
  [REQUEST_STATUS.PROCESSING]: 'Procesando',
  [REQUEST_STATUS.COMPLETED]: 'Completado',
  [REQUEST_STATUS.FAILED]: 'Error',
  [REQUEST_STATUS.REJECTED]: 'Rechazado',
  [REQUEST_STATUS.CANCELLED]: 'Cancelada',
};

export const JOB_STATUS_LABELS: Record<string, string> = {
  [JOB_STATUS.QUEUED]: 'En cola',
  [JOB_STATUS.PROCESSING]: 'Procesando',
  [JOB_STATUS.COMPLETED]: 'Completado',
  [JOB_STATUS.FAILED]: 'Error',
};
